/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BikeNumber = string;
export interface CustomerProfile {
  'bikeNumber' : BikeNumber,
  'name' : string,
  'kmReading' : bigint,
  'bikeModel' : string,
  'address' : string,
  'phone' : string,
  'fuelLevel' : string,
}
export interface Invoice {
  'id' : string,
  'status' : string,
  'createdAt' : Time,
  'serviceRecord' : ServiceRecord,
  'customerId' : bigint,
}
export interface ServiceRecord {
  'sparePartsCost' : bigint,
  'serviceType' : ServiceType,
  'total' : bigint,
  'createdAt' : Time,
  'gstAmount' : bigint,
  'labourCharges' : bigint,
  'concierge' : string,
  'discount' : bigint,
  'customService' : string,
  'gstFlag' : boolean,
  'customerId' : bigint,
  'subtotal' : bigint,
}
export interface ServiceType {
  'oilChange' : boolean,
  'engineRepair' : boolean,
  'generalService' : boolean,
  'spareParts' : boolean,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCustomerProfile' : ActorMethod<[CustomerProfile], bigint>,
  'createServiceRecord' : ActorMethod<[bigint, ServiceRecord], string>,
  'deleteCustomerProfile' : ActorMethod<[bigint], undefined>,
  'getAllCustomerProfiles' : ActorMethod<[], Array<[bigint, CustomerProfile]>>,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerProfile' : ActorMethod<[bigint], CustomerProfile>,
  'getDailySalesTotal' : ActorMethod<[], bigint>,
  'getInvoice' : ActorMethod<[string], Invoice>,
  'getMonthlySalesTotal' : ActorMethod<[], bigint>,
  'getPendingInvoices' : ActorMethod<[], Array<Invoice>>,
  'getServiceFrequency' : ActorMethod<[], Array<[string, bigint]>>,
  'getServiceHistoryByBikeNumber' : ActorMethod<[string], Array<Invoice>>,
  'getServiceRecord' : ActorMethod<[string], Invoice>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCustomerProfile' : ActorMethod<[bigint, CustomerProfile], undefined>,
  'updateInvoiceStatus' : ActorMethod<[string, string], undefined>,
  'updateServiceRecord' : ActorMethod<[string, ServiceRecord], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];