/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BikeNumber = IDL.Text;
export const CustomerProfile = IDL.Record({
  'bikeNumber' : BikeNumber,
  'name' : IDL.Text,
  'kmReading' : IDL.Nat,
  'bikeModel' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'fuelLevel' : IDL.Text,
});
export const ServiceType = IDL.Record({
  'oilChange' : IDL.Bool,
  'engineRepair' : IDL.Bool,
  'generalService' : IDL.Bool,
  'spareParts' : IDL.Bool,
});
export const Time = IDL.Int;
export const ServiceRecord = IDL.Record({
  'sparePartsCost' : IDL.Nat,
  'serviceType' : ServiceType,
  'total' : IDL.Nat,
  'createdAt' : Time,
  'gstAmount' : IDL.Nat,
  'labourCharges' : IDL.Nat,
  'concierge' : IDL.Text,
  'discount' : IDL.Nat,
  'customService' : IDL.Text,
  'gstFlag' : IDL.Bool,
  'customerId' : IDL.Nat,
  'subtotal' : IDL.Nat,
});
export const Invoice = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'createdAt' : Time,
  'serviceRecord' : ServiceRecord,
  'customerId' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCustomerProfile' : IDL.Func([CustomerProfile], [IDL.Nat], []),
  'createServiceRecord' : IDL.Func([IDL.Nat, ServiceRecord], [IDL.Text], []),
  'deleteCustomerProfile' : IDL.Func([IDL.Nat], [], []),
  'getAllCustomerProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, CustomerProfile))],
      ['query'],
    ),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerProfile' : IDL.Func([IDL.Nat], [CustomerProfile], ['query']),
  'getDailySalesTotal' : IDL.Func([], [IDL.Nat], ['query']),
  'getInvoice' : IDL.Func([IDL.Text], [Invoice], ['query']),
  'getMonthlySalesTotal' : IDL.Func([], [IDL.Nat], ['query']),
  'getPendingInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getServiceFrequency' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getServiceHistoryByBikeNumber' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Invoice)],
      ['query'],
    ),
  'getServiceRecord' : IDL.Func([IDL.Text], [Invoice], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCustomerProfile' : IDL.Func([IDL.Nat, CustomerProfile], [], []),
  'updateInvoiceStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateServiceRecord' : IDL.Func([IDL.Text, ServiceRecord], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BikeNumber = IDL.Text;
  const CustomerProfile = IDL.Record({
    'bikeNumber' : BikeNumber,
    'name' : IDL.Text,
    'kmReading' : IDL.Nat,
    'bikeModel' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'fuelLevel' : IDL.Text,
  });
  const ServiceType = IDL.Record({
    'oilChange' : IDL.Bool,
    'engineRepair' : IDL.Bool,
    'generalService' : IDL.Bool,
    'spareParts' : IDL.Bool,
  });
  const Time = IDL.Int;
  const ServiceRecord = IDL.Record({
    'sparePartsCost' : IDL.Nat,
    'serviceType' : ServiceType,
    'total' : IDL.Nat,
    'createdAt' : Time,
    'gstAmount' : IDL.Nat,
    'labourCharges' : IDL.Nat,
    'concierge' : IDL.Text,
    'discount' : IDL.Nat,
    'customService' : IDL.Text,
    'gstFlag' : IDL.Bool,
    'customerId' : IDL.Nat,
    'subtotal' : IDL.Nat,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'createdAt' : Time,
    'serviceRecord' : ServiceRecord,
    'customerId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCustomerProfile' : IDL.Func([CustomerProfile], [IDL.Nat], []),
    'createServiceRecord' : IDL.Func([IDL.Nat, ServiceRecord], [IDL.Text], []),
    'deleteCustomerProfile' : IDL.Func([IDL.Nat], [], []),
    'getAllCustomerProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, CustomerProfile))],
        ['query'],
      ),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerProfile' : IDL.Func([IDL.Nat], [CustomerProfile], ['query']),
    'getDailySalesTotal' : IDL.Func([], [IDL.Nat], ['query']),
    'getInvoice' : IDL.Func([IDL.Text], [Invoice], ['query']),
    'getMonthlySalesTotal' : IDL.Func([], [IDL.Nat], ['query']),
    'getPendingInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getServiceFrequency' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getServiceHistoryByBikeNumber' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Invoice)],
        ['query'],
      ),
    'getServiceRecord' : IDL.Func([IDL.Text], [Invoice], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCustomerProfile' : IDL.Func([IDL.Nat, CustomerProfile], [], []),
    'updateInvoiceStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateServiceRecord' : IDL.Func([IDL.Text, ServiceRecord], [], []),
  });
};

export const init = ({ IDL }) => { return []; };